"""Framework-neutral neural-network compute and memory cost analysis."""

try:
    from importlib.metadata import PackageNotFoundError
    from importlib.metadata import version as _version

    try:
        __version__ = _version("neural-cost")
    except PackageNotFoundError:
        __version__ = "0.7.0.dev0"
except ImportError:
    __version__ = "0.7.0.dev0"

from .adapters import available_adapters, get_adapter
from .analysis import (
    ContinuousBatchGapAnalysis,
    DistributedGapAnalysis,
    GapAnalysis,
    KernelLaunchAnalysis,
    LayerGapAnalysis,
    MemoryGapAnalysis,
    ModelGapAnalysis,
    MoEGapAnalysis,
    PagedAttentionGapAnalysis,
    SpeculativeDecodingAnalysis,
    SSMGapAnalysis,
    analyze_continuous_batch_iteration,
    analyze_distributed_gap,
    analyze_gap,
    analyze_kernel_launch_floor,
    analyze_layers_gap,
    analyze_memory_gap,
    analyze_model_gap,
    analyze_moe_gap,
    analyze_paged_attention_gap,
    analyze_speculative_decoding,
    analyze_ssm_gap,
)
from .api import estimate_model
from .checkpointing import (
    ActivationCheckpointingEstimate,
    ActivationCheckpointingGapAnalysis,
    CheckpointingStrategy,
    analyze_activation_checkpointing,
    estimate_activation_checkpointing,
)
from .estimate import (
    ContinuousBatchIterationEstimate,
    CostEstimate,
    FusedCostEstimate,
    MoECostEstimate,
    PagedAttentionCostEstimate,
    ParallelismCostEstimate,
    SpeculativeCostEstimate,
    SSMCostEstimate,
    estimate_adamw_traffic,
    estimate_continuous_batch_iteration,
    estimate_conv2d,
    estimate_fused_operations,
    estimate_moe,
    estimate_operation,
    estimate_operations,
    estimate_paged_attention,
    estimate_parallelism,
    estimate_speculative_decoding,
    estimate_ssm,
)
from .hardware import (
    INTERCONNECT_PRESETS,
    CacheSpec,
    ClusterTopology,
    HardwareSpec,
    InterconnectSpec,
    get_interconnect_preset,
)
from .hardware_detect import DetectionResult, detect_hardware
from .memory import MemoryEstimate, estimate_memory
from .model import ModelProfile, profile_model
from .operations import Operation
from .profiler import Measurement, benchmark
from .quantization import (
    PRECISION_FORMATS,
    QUANTIZATION_PRESETS,
    DequantizationCostEstimate,
    PrecisionFormat,
    QuantizationGapAnalysis,
    QuantizationSpec,
    analyze_quantization_gap,
    estimate_quantized_linear,
    get_precision_format,
    get_quantization_preset,
)

__all__ = [
    "INTERCONNECT_PRESETS",
    "PRECISION_FORMATS",
    "QUANTIZATION_PRESETS",
    "ActivationCheckpointingEstimate",
    "ActivationCheckpointingGapAnalysis",
    "CacheSpec",
    "CheckpointingStrategy",
    "ClusterTopology",
    "ContinuousBatchGapAnalysis",
    "ContinuousBatchIterationEstimate",
    "CostEstimate",
    "DequantizationCostEstimate",
    "DetectionResult",
    "DistributedGapAnalysis",
    "FusedCostEstimate",
    "GapAnalysis",
    "HardwareSpec",
    "InterconnectSpec",
    "KernelLaunchAnalysis",
    "LayerGapAnalysis",
    "Measurement",
    "MemoryEstimate",
    "MemoryGapAnalysis",
    "MoECostEstimate",
    "MoEGapAnalysis",
    "ModelGapAnalysis",
    "ModelProfile",
    "Operation",
    "PagedAttentionCostEstimate",
    "PagedAttentionGapAnalysis",
    "ParallelismCostEstimate",
    "PrecisionFormat",
    "QuantizationGapAnalysis",
    "QuantizationSpec",
    "SSMCostEstimate",
    "SSMGapAnalysis",
    "SpeculativeCostEstimate",
    "SpeculativeDecodingAnalysis",
    "__version__",
    "analyze_activation_checkpointing",
    "analyze_continuous_batch_iteration",
    "analyze_distributed_gap",
    "analyze_gap",
    "analyze_kernel_launch_floor",
    "analyze_layers_gap",
    "analyze_memory_gap",
    "analyze_model_gap",
    "analyze_moe_gap",
    "analyze_paged_attention_gap",
    "analyze_quantization_gap",
    "analyze_speculative_decoding",
    "analyze_ssm_gap",
    "available_adapters",
    "benchmark",
    "detect_hardware",
    "estimate_activation_checkpointing",
    "estimate_adamw_traffic",
    "estimate_continuous_batch_iteration",
    "estimate_conv2d",
    "estimate_fused_operations",
    "estimate_memory",
    "estimate_model",
    "estimate_moe",
    "estimate_operation",
    "estimate_operations",
    "estimate_paged_attention",
    "estimate_parallelism",
    "estimate_quantized_linear",
    "estimate_speculative_decoding",
    "estimate_ssm",
    "get_adapter",
    "get_interconnect_preset",
    "get_precision_format",
    "get_quantization_preset",
    "profile_model",
]
